Use prosemirror document for showing and saving comments (LEAN-2322)
Atypon-OpenSource/manuscripts-article-editor pull request #170
Opened 2023-03-23 11:51 UTC by asouqi

I added a dedicated callback for saving and deleting comments, as we can't add that logic in `saveTrackModel` will make it more complex and hard to read

2023-03-24 12:31 UTC, asouqi commented on src/hooks/use-tracked-model-management.ts
> +  const saveCommentNode = useCallback(
updated to encapsulate saveCommentNode in saveTrackModel

2023-03-24 17:01 UTC, mbartenev-atypon requested changes

2023-03-24 17:01 UTC, mbartenev-atypon commented on src/hooks/use-tracked-model-management.ts
> +        id: comment._id,
Ok, but do we have a node that correspond to a comment at all? Is that it (on the screen below)? I'm sorry I am a bit at a loss here, it seems like we add some attributes that are not in the schema.
<img width="341" alt="image" src="https://user-images.githubusercontent.com/40764175/227591749-1bb75b11-c0f7-42a5-b0a4-5975447f5197.png">

2023-03-24 20:25 UTC, asouqi commented on src/hooks/use-tracked-model-management.ts
> +        id: comment._id,
oh I forget to tell you there is a [PR#9](https://github.com/Atypon-OpenSource/manuscripts-transform/pull/9/files) to add them for comment node

2023-03-27 15:43 UTC, mbartenev-atypon approved these changes

2023-04-09 14:36 UTC, merged