LEAN-1172 - Replace file functionality - UI implementation
Atypon-OpenSource/manuscripts-article-editor pull request #27
Opened 2022-06-02 09:53 UTC by jirikaiser-atypon

2022-06-02 16:13 UTC, mbartenev-atypon requested changes

2022-06-03 11:40 UTC, dmone90 commented
rerun

2022-06-06 08:56 UTC, jirikaiser-atypon commented on src/components/projects/lean-workflow/FileHandling.tsx
> +        figureModel.externalFileReferences[
Fixed

2022-06-06 08:56 UTC, jirikaiser-atypon commented on src/components/projects/lean-workflow/Inspector.tsx
> +                      handleUpdateInline={handleUpdateInlineFile}
Fixed in the style guide

2022-06-06 11:02 UTC, mbartenev-atypon approved these changes

2022-06-06 11:10 UTC, mbartenev-atypon approved these changes

2022-06-06 14:31 UTC, merged